#!/bin/bash

set -xeufo pipefail

LOCALCMD=`realpath $0`
LOCALDIR=`dirname $LOCALCMD`

function convert_argv {
    argv=""
    while (($#)); do
        if [ -e $1 ] ; then
            arg=`WINEDEBUG=-all winepath -w $1`
        else
            arg=$1
        fi
        argv="$argv $arg"
        shift
    done
    echo $argv
}

WINEDEBUG=-all wine $LOCALDIR/adl.exe `convert_argv $@`

ret=$?

if [ ret -eq 127 ] ; then
  ret=0
fi

exit $ret
