#!/bin/bash

set -xeufo pipefail

export LOCALDIR=`dirname $0`
export WINEPREFIX=/wineprefix
export WINEARCH=win32
export WINEDEBUG=-all

function convert_argv {
    argv=""
    while (($#)); do
        if [ -e $1 ] ; then
            arg=`winepath -w $1`
        else
            arg=$1
        fi
        argv="$argv $arg"
        shift
    done
    echo $argv
}

wine $LOCALDIR/adl.exe `convert_argv $@`

ret=$?

if [ ret -eq 127 ] ; then
  ret=0
fi

exit $ret
